In [1]:
from pycocotools.coco import COCO
coco = COCO(annotation_file="/home/zjl/桌面/project/data/cocoData/annotations/instances_val2017.json")
ids = coco.getCatIds('person')[0]
imgids = coco.catToImgs[ids]

loading annotations into memory...
Done (t=0.34s)
creating index...
index created!


In [2]:
coco.loadImgs(425226)[0]['file_name']

'000000425226.jpg'

In [3]:
int('000000425226')

425226

In [4]:
fn = lambda x : (0.01 * (1 - (1-0.01)/300 * x))

In [5]:
fn(300)

0.00010000000000000009

In [6]:
import torch
import torch.nn as nn
from torch.optim.lr_scheduler import LambdaLR

initial_lr = 0.1

class model(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(in_channels=3, out_channels=3, kernel_size=3)

    def forward(self, x):
        pass

net_1 = model()

optimizer_1 = torch.optim.Adam(net_1.parameters(), lr = 0.01)
fn = lambda x : (1 - (1-0.01)/10 * x) 
scheduler_1 = LambdaLR(optimizer_1, lr_lambda=fn)

print("初始化的学习率：", optimizer_1.defaults['lr'])

for epoch in range(1, 11):
    # train

    optimizer_1.zero_grad()
    optimizer_1.step()
    print("第%d个epoch的学习率：%f" % (epoch, optimizer_1.param_groups[0]['lr']))
    scheduler_1.step()


初始化的学习率： 0.01
第1个epoch的学习率：0.010000
第2个epoch的学习率：0.009010
第3个epoch的学习率：0.008020
第4个epoch的学习率：0.007030
第5个epoch的学习率：0.006040
第6个epoch的学习率：0.005050
第7个epoch的学习率：0.004060
第8个epoch的学习率：0.003070
第9个epoch的学习率：0.002080
第10个epoch的学习率：0.001090


/home/zjl/anaconda3/envs/normal/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [7]:
xlist = torch.arange(0.5, 100)
ylist = torch.arange(0.5, 100)
y, x = torch.meshgrid(ylist, xlist, indexing='ij')

In [8]:
import numpy as np
xxlist = np.arange(0.5, 100)
yylist = np.arange(0.5, 100)
xx, yy = np.meshgrid(xxlist, yylist)

In [9]:
yy

array([[ 0.5,  0.5,  0.5, ...,  0.5,  0.5,  0.5],
       [ 1.5,  1.5,  1.5, ...,  1.5,  1.5,  1.5],
       [ 2.5,  2.5,  2.5, ...,  2.5,  2.5,  2.5],
       ...,
       [97.5, 97.5, 97.5, ..., 97.5, 97.5, 97.5],
       [98.5, 98.5, 98.5, ..., 98.5, 98.5, 98.5],
       [99.5, 99.5, 99.5, ..., 99.5, 99.5, 99.5]])

In [10]:
a = torch.randn(2,4)
print(a)
a[:, [1,3]] += 1
print(a)

tensor([[-1.5248,  0.2664, -0.0234, -0.4654],
        [ 0.3674, -1.2649,  1.8550,  1.4748]])
tensor([[-1.5248,  1.2664, -0.0234,  0.5346],
        [ 0.3674, -0.2649,  1.8550,  2.4748]])


In [11]:
from net.yolo8 import Yolo8
backbone = Yolo8(80, 's', True).backbone
# print(backbone)
print(len(list(backbone.state_dict().items())))

162


n-162

l-306

m-234

x-306

s-162

In [14]:
optimizer_1.param_groups[1]['lr']

IndexError: list index out of range